include @@THEOS@@/makefiles/common.mk

TWEAK_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = @@PROJECTNAME@@.m
@@PROJECTNAME@@_FRAMEWORKS = UIKit
@@PROJECTNAME@@_LDFLAGS = -lactivityloader

include $(THEOS_MAKE_PATH)/tweak.mk
